name: Extract Kernel Headers

on:
  workflow_dispatch:

jobs:
  extract-headers:
    runs-on: ubuntu-latest
    env:
      ARCH: arm64
      CROSS_COMPILE: aarch64-linux-gnu-

    steps:
    # Step 1: Checkout the kernel source
    - name: Checkout Kernel Source
      uses: actions/checkout@v4
      with:
        submodules: "true"
        fetch-depth: 100

    # Step 2: Install dependencies
    - name: Install Dependencies
      run: |
        sudo apt-get update -y
        sudo apt-get install -y \
          gcc-aarch64-linux-gnu \
          make \
          bc \
          flex \
          bison \
          libssl-dev \
          libelf-dev \
          build-essential

    # Step 3: Set up kernel config
    - name: Configure Kernel
      run: |
        make ARCH=$ARCH CROSS_COMPILE=$CROSS_COMPILE defconfig
        make ARCH=$ARCH CROSS_COMPILE=$CROSS_COMPILE prepare
        make ARCH=$ARCH CROSS_COMPILE=$CROSS_COMPILE headers_install INSTALL_HDR_PATH=output_headers

    # Step 4: Upload Headers as Artifact
    - name: Upload Kernel Headers
      uses: actions/upload-artifact@v4
      with:
        name: Kernel_Headers
        path: output_headers/
